/*
 * This source file was generated by the Gradle 'init' task
 */
package me.dio.boot;

public class App {
    public static void main(String[] args) {
        Bootcamp boot_java = new Bootcamp("DIO - JAVA SANTANDER");
        
        Topico t0 = new Topico("Tipos de dados");
        Topico t1 = new Topico("Estruturas de controle de fluxo");
        Topico t2 = new Topico("Estruturas de repetição");

        Atividade inicio = new Atividade("Java Basico");
        inicio.adicionar(t0);
        inicio.adicionar(t1);
        inicio.adicionar(t2);


        boot_java.adicionar(inicio);
        boot_java.mostrar_todas_as_aulas();
    }
}

